# Generated by Django 4.0 on 2021-12-20 16:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 20, 16, 41, 17, 162698, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
