# Generated by Django 4.0 on 2021-12-21 05:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_newsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 21, 5, 4, 13, 567252, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
