# Generated by Django 4.0 on 2022-01-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_newsrecord_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
